export const GAMES = [
    "Keepy Uppy (Season 1, Episode 3)",
    "Shadowlands (Season 1, Episode 5)",
    "Grannies (Season 1, Episode 23)",
    "Magic Xylophone (Season 2, Episode 1)",
    "The Claw (Season 1, Episode 14)",
    "Don't Drop the Egg (Season 2, Episode 25)",
    "Pass the Parcel (Season 3, Episode 13)",
    "Cave (Season 3, Episode 3)",
    "The Sleepover (Season 2, Episode 20)",
    "Musical Statues (Season 2, Episode 22)",
    "Obstacle Course (Season 1, Episode 7)",
    "Game Show (Season 1, Episode 10)",
    "Dance Mode (Season 2, Episode 8)",
    "The Quiet Game (Season 1, Episode 16)",
    "Mums and Dads (Season 1, Episode 6)",
    "Hospital (Season 2, Episode 12)",
    "Store (Season 1, Episode 24)",
    "Cricket (Season 3, Episode 1)",
    "Playground (Season 1, Episode 2)",
    "Spooky (Season 1, Episode 15)",
    "House (Season 1, Episode 11)",
    "Pirates (Season 1, Episode 18)",
    "Superheroes (Season 2, Episode 14)",
    "Camping (Season 3, Episode 7)",
    "Postman (Season 2, Episode 24)"
  ];
  
  export const EPISODE = [
    "Born Yesterday (Season 3, Episode 25)",
    "The Sign (Season 3, Episode 26)",
    "The Beach (Season 1, Episode 1)",
    "Takeaway (Season 1, Episode 14)",
    "Calypso (Season 1, Episode 17)",
    "The Claw (Season 1, Episode 14)",
    "Sleepytime (Season 2, Episode 26)",
    "Granny Mobile (Season 2, Episode 6)",
    "Cricket (Season 3, Episode 1)",
    "Baby Race (Season 2, Episode 50)",
    "Grannies (Season 1, Episode 23)",
    "Camping (Season 3, Episode 7)",
    "Dance Mode (Season 2, Episode 8)",
    "Rain (Season 2, Episode 9)",
    "Christmas Swim (Season 2, Episode 10)",
    "Bin Night (Season 2, Episode 11)",
    "Army (Season 2, Episode 12)",
    "Tradies (Season 2, Episode 13)",
    "Pass the Parcel (Season 3, Episode 13)",
    "Hammerbarn (Season 3, Episode 14)",
    "Faceytalk (Season 3, Episode 15)",
    "Unicorse (Season 3, Episode 16)",
    "Bingo (Season 3, Episode 17)",
    "Cubby (Season 3, Episode 18)",
    "Turtleboy (Season 3, Episode 19)"
  ];
  
  export const CHILI = [
    "Remember, I'll always be here for you. Even if you can't see me. Because I love you. (Season 2, Episode 26)",
    "Remember, the truth will set you free. (Season 3, Episode 9)",
    "Let's get all this stuff up to the unit and head straight to the beach. I wanna start relaxing. (Season 2, Episode 47)",
    "I have a little cry, then I pick myself up, dust myself off, and keep going. The show must go on. (Season 2, Episode 16)",
    "You're doing great. (Season 2, Episode 50)",
    "Work on the heads later, for now, just hearts. (Season 3, Episode 25)",
    "You kids need to start using your energy to help me! (Season 2, Episode 3)",
    "If you get knocked down, you just get back up again. (Season 2, Episode 17)",
    "I'm your mother. It's my job to train you up. (Season 3, Episode 41)",
    "You don't have to be having fun to have fun. (Season 2, Episode 24)",
    "Everyone fails mum school sometimes. (Season 3, Episode 38)",
    "You've got to learn to lose. (Season 3, Episode 51)",
    "Okay, you can have your money back. (Season 2, Episode 8)",
    "Sometimes, the best things in life happen by accident. (Season 3, Episode 29)",
    "You're never fully dressed without a smile. (Season 1, Episode 31)",
    "Sometimes, you just have to take a deep breath and jump in. (Season 1, Episode 29)",
    "Just because things are different, doesn't mean they're not good. (Season 2, Episode 23)",
    "Don't stress, you'll be okay. (Season 3, Episode 28)",
    "You're ready, you just don't know it yet. (Season 3, Episode 14)",
    "Sometimes we have to take time to stop and appreciate what's around us. (Season 3, Episode 5)",
    "It's okay to change your mind. (Season 3, Episode 34)",
    "The best way to show love is by listening. (Season 2, Episode 30)",
    "It's okay to feel hurt, but you need to talk about it. (Season 2, Episode 32)"
  ];